DROP TABLE IF EXISTS USERINFO;
 
CREATE TABLE USERINFO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250)  NULL,
  last_name VARCHAR(250)  NULL,
  email VARCHAR(250) NOT NULL,
  pincode INT(20) NOT NULL,
  birthdate DATE NOT NULL
);